# Configuración del servidor
server.port=8085

# Conexión a la Base de Datos MySQL (Asegúrate de cambiar 'sga_db', tu usuario y contraseña si difieren)
spring.datasource.url=jdbc:mysql://localhost:3306/sga_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de Thymeleaf (para desarrollo en caliente)
spring.thymeleaf.cache=false