### 1. Obtener todas las ubicaciones
GET http://localhost:8085/api/locations

### 2. Obtener una ubicación por ID
GET http://localhost:8085/api/locations/1

### 3. Crear una nueva ubicación
POST http://localhost:8085/api/locations
Content-Type: application/json

{
    "locationCode": "B-02-05",
    "zone": "Zona Sur",
    "available": true
}

### 4. Eliminar una ubicación por ID
DELETE http://localhost:8085/api/locations/2